# Dependencies
markdown:         redcarpet
pygments:         true
redcarpet:
  extensions:     [smart]

# Permalinks
permalink:        pretty

# Setup
title:            Martin Spier
tagline:          'Performance Engineer'
description:      'Performance Engineer @ Netflix. Investor. Occasional DJ. Addicted to Travel and Electronic Music.<br>Bay Area, CA'
url:              http://perf.guru

author:
  name:             'Martin Spier'
  url:              https://twitter.com/spiermar

paginate:         5

# Custom vars
version:          1.0.0

github: 
  url:             https://github.com/spiermar

linkedin: 
  url:             https://www.linkedin.com/in/martinspier
