# Dependencies
markdown:         kramdown
highlander:       pygments
redcarpet:
  extensions:     [smart]

gems:             []

# Permalinks
permalink:        pretty

# Setup
title:            Martin Spier
tagline:          'Making things fast again.'
about:            'Performance Engineer @ Netflix.<br>Advisor @ monashees+.<br>Entrepreneur. Adventurer.<br>Addicted to Travel and Electronic Music.<br>Bay Area, CA'
url:              http://martinspier.io

author:
  name:           'Martin Spier'
  url:            https://twitter.com/spiermar

# Custom vars
version:          1.0.0

github:
  url:             https://github.com/spiermar

linkedin:
  url:             https://www.linkedin.com/in/martinspier

medium:
  url:             https://medium.com/@mspier

instagram:
  url:             https://www.instagram.com/unchartedcorners